/**
 * Tool: report_cleanup_opportunity — record a cleanup finding (path, size, description, why safe).
 * Appends to an in-memory accumulator; report is written when the run completes.
 */

import { tool } from "@langchain/core/tools";
import { z } from "zod";
import type { CleanupOpportunity } from "@/services/reportTypes.js";

export interface ReportAccumulator {
  push(opportunity: CleanupOpportunity): void;
}

export function createReportCleanupOpportunityTool(accumulator: ReportAccumulator) {
  const func = (input: {
    path: string;
    pathDescription: string;
    sizeBytes: number;
    contentsDescription: string;
    whySafeToDelete: string;
    suggestedAction?: string;
  }) => {
    accumulator.push({
      path: input.path,
      pathDescription: input.pathDescription,
      sizeBytes: input.sizeBytes,
      contentsDescription: input.contentsDescription,
      whySafeToDelete: input.whySafeToDelete,
      suggestedAction: input.suggestedAction,
    });
    return `Recorded cleanup opportunity: ${input.path} (${input.sizeBytes} bytes)`;
  };
  return tool(func as (input: unknown) => string, {
      name: "report_cleanup_opportunity",
      description:
        "Record a cleanup opportunity you found. Provide: path, short pathDescription, sizeBytes, contentsDescription (what is in there), whySafeToDelete (why it is safe or okay to delete), and optional suggestedAction. Call this for each location the user can safely clean.",
      schema: z.object({
        path: z.string().describe("Filesystem path of the folder or item."),
        pathDescription: z.string().describe("Short human-readable description of the path (e.g. 'npm cache directory')."),
        sizeBytes: z.number().describe("Size in bytes that can be freed."),
        contentsDescription: z.string().describe("Overall description of what is in there (e.g. cache files, old logs)."),
        whySafeToDelete: z.string().describe("Why it is safe or okay to delete (e.g. regenerated by app, temporary)."),
        suggestedAction: z.string().optional().describe("Optional suggested action (e.g. 'Delete entire folder')."),
      }),
    }
  );
}
