/**
 * Tool: report_cleanup_opportunity — record one or more cleanup findings (path, size, description, why safe).
 * Appends to an in-memory accumulator; report is written when the run completes.
 * Supports batch reporting to reduce tool calls when the agent has multiple opportunities.
 */

import { tool } from "@langchain/core/tools";
import { z } from "zod";
import type { CleanupOpportunity } from "@/services/reportTypes.js";

export interface ReportAccumulator {
  push(opportunity: CleanupOpportunity): void;
}

const opportunitySchema = z.object({
  path: z.string().describe("Filesystem path of the folder or item."),
  pathDescription: z.string().describe("Short human-readable description of the path (e.g. 'npm cache directory')."),
  sizeBytes: z.number().describe("Size in bytes that can be freed."),
  contentsDescription: z.string().describe("Overall description of what is in there (e.g. cache files, old logs)."),
  whySafeToDelete: z.string().describe("Why it is safe or okay to delete (e.g. regenerated by app, temporary)."),
  suggestedAction: z.string().optional().describe("Optional suggested action (e.g. 'Delete entire folder')."),
});

export function createReportCleanupOpportunityTool(accumulator: ReportAccumulator) {
  const func = (input: { opportunities: Array<z.infer<typeof opportunitySchema>> }) => {
    for (const opp of input.opportunities) {
      accumulator.push({
        path: opp.path,
        pathDescription: opp.pathDescription,
        sizeBytes: opp.sizeBytes,
        contentsDescription: opp.contentsDescription,
        whySafeToDelete: opp.whySafeToDelete,
        suggestedAction: opp.suggestedAction,
      });
    }
    const totalBytes = input.opportunities.reduce((sum, o) => sum + o.sizeBytes, 0);
    const count = input.opportunities.length;
    return count === 1
      ? `Recorded 1 cleanup opportunity: ${input.opportunities[0].path} (${input.opportunities[0].sizeBytes} bytes)`
      : `Recorded ${count} cleanup opportunities (${totalBytes} bytes total)`;
  };
  return tool(func as (input: unknown) => string, {
    name: "report_cleanup_opportunity",
    description:
      "Record one or more cleanup opportunities in a single call. Pass an array 'opportunities' where each item has: path, pathDescription, sizeBytes, contentsDescription, whySafeToDelete, and optional suggestedAction. Prefer batching multiple findings into one call when you have several to report.",
    schema: z.object({
      opportunities: z
        .array(opportunitySchema)
        .min(1)
        .describe("One or more cleanup opportunities to record."),
    }),
  });
}
